- name: import MongoDB public GPG Key
  action: command apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

- name: add MongoDB repository to APT sources
  action: copy
          src=$ansible/templates/10gen.list
          dest=/etc/apt/sources.list.d/10gen.list
          owner=root group=root mode=0644

- action: command apt-get update

- name: install MongoDB
  action: apt pkg=mongodb-10gen